
export const enum EventAction {
  SET_VISIBLE = 'SET_VISIBLE',
  SET_POSITION = 'SET_POSITION',
  SET_DECORATING_TEXT = 'SET_DECORATING_TEXT',
  SET_INTERACTING = 'SET_INTERACTING',
  SET_NOT_INTERACTING = 'SET_NOT_INTERACTING',
  MOVE_NEAR = 'MOVE_NEAR',
  MOVE_NEAR_CELL = 'MOVE_NEAR_CELL',
  SET_TINT_COLOR = 'SET_TINT_COLOR',
  SET_SPRITE_FRAME = 'SET_SPRITE_FRAME',
  RESOURCE_SET_CAPACITY = 'RESOURCE.SET_CAPACITY',
  RESOURCE_SET_UTILIZATION = 'RESOURCE.SET_UTILIZATION',
  CONTAINER_SET_LEVEL = 'CONTAINER.SET_LEVEL',
  CONTAINER_SET_CAPACITY = 'CONTAINER.SET_CAPACITY',
  STORE_SET_CAPACITY = 'STORE.SET_CAPACITY',
  STORE_SET_CONTENT = 'STORE.SET_CONTENT'
}
