name: Lint Simplay Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          cd src/simplay
          python -m build
      - name: Format package
        run: |
          cd src/simplay
          python -m pip install --upgrade pip
          pip install autopep8
          pip install dist/*.whl
          python -m autopep8 --in-place --aggressive --aggressive --recursive src/simplay
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Linting"
          add: "src/simplay"
          force: true
      - name: Lint package
        run: |
          cd src/simplay
          python -m pip install --upgrade pip
          pip install flake8
          pip install dist/*.whl
          python -m flake8 src/simplay
