on:
  pull_request:
    paths:
      - 'src/simplay-web/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
        cd src/simplay-web
        npm i
        npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        cd src/simplay-web
        npm i
        npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        cd src/simplay-web
        npm i
        npm run build