on:
  pull_request:
    paths:
      - 'src/simplay-web/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: |
          cd src/simplay-web
          npm i
          npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: |
          cd src/simplay-web
          npm i
          npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run build 
        run: |
          cd src/simplay-web
          npm i
          npm run build